"""empty message

Revision ID: 170c7c96b41f
Revises: 5b881f69cc87
Create Date: 2022-08-09 13:31:06.190938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170c7c96b41f'
down_revision = '5b881f69cc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
